# Generated by Django 5.2.1 on 2025-06-12 17:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expensecategory_name_expensecategory_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
