# Generated by Django 5.2.1 on 2025-06-25 19:45

from django.db import migrations

def add_default_categories(apps, schema_editor):
    ExpenseCategory = apps.get_model('expenses', 'ExpenseCategory')
    ExpenseCategory.objects.get_or_create(name='Еда', is_default=True),
    ExpenseCategory.objects.get_or_create(name='Кафе', is_default=True),
    ExpenseCategory.objects.get_or_create(name='Развлечения', is_default=True),
    ExpenseCategory.objects.get_or_create(name='Транспорт', is_default=True),
    ExpenseCategory.objects.get_or_create(name='Здоровье', is_default=True),
    ExpenseCategory.objects.get_or_create(name='Питомцы', is_default=True),
    ExpenseCategory.objects.get_or_create(name='Семья', is_default=True),
    ExpenseCategory.objects.get_or_create(name='Одежда', is_default=True),
    ExpenseCategory.objects.get_or_create(name='Коммуналка', is_default=True),


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_expensecategory_date_created_and_more'),
    ]

    operations = [
    ]
