# Generated by Django 5.2.1 on 2025-06-08 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incomecategory',
            name='name',
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
