# Generated by Django 5.2.1 on 2025-06-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0004_remove_income_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomecategory',
            name='date_created',
            field=models.DateField(default='2025-06-06'),
        ),
        migrations.AddField(
            model_name='incomecategory',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
    ]
