# Generated by Django 5.2.1 on 2025-06-10 19:18

from django.db import migrations

def add_default_categories(apps, schema_editor):
    IncomeCategory = apps.get_model('incomes', 'IncomeCategory')
    IncomeCategory.objects.get_or_create(name='Зарплата', is_default=True)
    IncomeCategory.objects.get_or_create(name='Подарок', is_default=True)
    IncomeCategory.objects.get_or_create(name='Проценты', is_default=True)
    IncomeCategory.objects.get_or_create(name='Другое', is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0005_incomecategory_date_created_and_more'),
    ]

    operations = [migrations.RunPython(add_default_categories),
    ]
