# Generated by Django 5.2.1 on 2025-06-10 19:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0006_auto_20250610_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incomecategory',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
