# Generated by Django 5.2.1 on 2025-06-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0007_alter_incomecategory_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='incomecategory',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
