# Generated by Django 5.2.1 on 2025-07-15 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incomes', '0008_alter_income_date_alter_incomecategory_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
