# Generated by Django 5.2.1 on 2025-06-25 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0002_alter_balance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Текущий'), (2, 'Накопления')], default=1),
        ),
    ]
