# Generated by Django 5.2.1 on 2025-06-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0003_alter_balance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
