# Generated by Django 5.2.1 on 2025-07-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balances', '0006_alter_balance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
